// This file was generated by Cinnabar Forge Meta. Do not edit.

export default {
  "cinnabarMetaVersion": 1,
  "description": "Web-serve your folders in a snap using various view modes",
  "name": "SnapServe",
  "version": {
    "major": 0,
    "minor": 3,
    "patch": 2,
    "revision": 7,
    "text": "0.3.2",
    "timestamp": 1722116290
  },
  "stack": {
    "nodejs": {
      "outputFile": [
        "src",
        "cinnabar.js"
      ],
      "package": "snapserve"
    }
  }
};
